### ISSUE TITLE
26.2 version

### ISSUE THREAD

**Issue by TheDGOfficial** [MrCloudy2/hideyho#1]
Would appreciate a github release for MC 26.2.

```java
Mod 'Hideyho Solver' (hideyhosolver) 1.0.0+mc26.1.2 requires any version between 26.1 (inclusive) and 26.2- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 26.2!
```

When trying to run the 26.1.2 version bypassing the ~26.1 version constraint in fabric.mod.json, this crash is the result:

```java
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'hideyhosolver' at 'dev.rok.hideyho.HideyhoMod'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$0(FabricLoaderImpl.java:413)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:411)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at knot//net.minecraft.client.Minecraft.<init>(Minecraft.java:456)
	at java.base/java.lang.Thread.run(Thread.java:1516)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/MultiBufferSource
	at knot//dev.rok.hideyho.HideyhoMod.onInitializeClient(HideyhoMod.java:44)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:409)
	... 3 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.MultiBufferSource
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:502)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:239)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:502)
	... 5 more
```

Of course there will most likely be more crashes or issues once this one is fixed, so it's best to compile separately targeting MC 26.2 with Gradle and verify that the game launches for the Mixins to apply.
